data senic_f;
set senic;
run;
data senic_f;
set senic_f;
a=y; box='Hospital'; output;
drop a;
run;
data senic_f;
set senic_f;
lg_y=log(y);output;
run;

proc boxplot data=senic_f;
plot y*box/cframe=vligb boxstyle=schematic
boxwidth=5.0 idsymbol=star cboxes=dagr cboxfill=ywh;
title 'Boxplot for Y';
run;
proc boxplot data=senic_f;
plot lg_y*box/cframe=vligb boxstyle=schematic
boxwidth=5.0 idsymbol=star cboxes=dagr cboxfill=ywh;
title 'Boxplot for Log(Y)';
run;

proc capability data=senic_f noprint;
histogram y/normal vscale=count;
inset n mean(5.2)/cfill=ywh;
title 'Histogram for Y';
run;
proc capability data=senic_f noprint;
qqplot y;
title 'QQplot for Y';
run;

proc capability data=senic_f noprint;
histogram lg_y/normal vscale=count;
inset n mean(5.2)/cfill=ywh;
title 'Histograms for Log(Y)';
run;
proc capability data=senic_f noprint;
qqplot lg_y;
title 'QQplot for Log(Y)';
run;
proc sort data=senic_f;
by y;
run;
proc univariate data=senic_f noprint;
var y;
output out=out n=n median=median;
run;
data senic_f;
set senic_f;
if _N_=1 then set out;
run;

data senic_f;
set senic_f;
i=_N_;
L=median-y;
U=y-median;
keep L U n i;
run;

data senic_f1;
set senic_f;
if floor(n/2)=n/2 then do;
if i>n/2 then delete;
end;
if floor(n/2)<n/2 then do;
if i>(n+1)/2 then delete;
end;
keep U;
run;
data senic_f2;
set senic_f;
if floor(n/2)=n/2 then do;
if i<=n/2 then delete;
end;
if floor(n/2)<n/2 then do;
if i<(n+1)/2 then delete;
end;
keep L;
run;
proc sort data=senic_f1;
by U;
run;
proc sort data=senic_f2;
by L;
run;
data senic_f;
merge senic_f1 senic_f2;
run;
axis1 order=(-9 to 11 by 2) label=(a=90 'Distance below median') ;
axis2 order=(-9 to 11 by 2) label=(a=0 'Distance above median') ;
symbol interpol=none value=circle color=black height=.5;

proc gplot data=senic_f;
plot   L*U/vaxis=axis1 haxis=axis2;
title 'Symmetry Plot for Y';
run;
data senic_fc;
set senic;
run;
data senic_fc;
set senic_fc;
lg_y=log(y);output;
run;
proc sort data=senic_fc;
by lg_y;
run;
proc univariate data=senic_fc noprint;
var lg_y;
output out=out1 n=n median=median;
run;
data senic_fc;
set senic_fc;
if _N_=1 then set out1;
run;

data senic_fc;
set senic_fc;
i=_N_;
L=median-lg_y;
U=lg_y-median;
keep L U n i;
run;

data senic_fc1;
set senic_fc;
if floor(n/2)=n/2 then do;
if i>n/2 then delete;
end;
if floor(n/2)<n/2 then do;
if i>(n+1)/2 then delete;
end;
keep U;
run;
data senic_fc2;
set senic_fc;
if floor(n/2)=n/2 then do;
if i<=n/2 then delete;
end;
if floor(n/2)<n/2 then do;
if i<(n+1)/2 then delete;
end;
keep L;
run;
proc sort data=senic_fc1;
by U;
run;
proc sort data=senic_fc2;
by L;
run;
data senic_fc;
merge senic_fc1 senic_fc2;
run;
axis3 order=(-.8 to .2 by .2) label=(a=90 'Distance below median') ;
axis4 order=(-.8 to .2 by .2) label=(a=0 'Distance above median') ;
proc gplot data=senic_fc;
plot   L*U/vaxis=axis3 haxis=axis4;
title 'Symmetry Plot for Log(Y)';
run;
